### ISSUE TITLE
Add lighting button with layer

### ISSUE THREAD

**Issue by PhyberApex** [PhyberApex/homeassistant-config#74]
```
        - name: Buttons
          entities:
            - input_boolean.floorplan_toggle_sonos_button
          layer_toggle: true
          action:
            service: toggle
```
